-- =============================================================================
-- Roles and Permissions
-- =============================================================================

USE ROLE SECURITYADMIN;

-- ----- Roles -----
CREATE ROLE IF NOT EXISTS FIVETRAN_ROLE
    COMMENT = 'Role used by the Fivetran service account';

CREATE ROLE IF NOT EXISTS DBT_ROLE
    COMMENT = 'Role used by dbt for transformations';

CREATE ROLE IF NOT EXISTS ANALYST_ROLE
    COMMENT = 'Read-only role for BI tools and analysts';

-- Role hierarchy: SYSADMIN -> DBT_ROLE / FIVETRAN_ROLE
GRANT ROLE FIVETRAN_ROLE TO ROLE SYSADMIN;
GRANT ROLE DBT_ROLE      TO ROLE SYSADMIN;
GRANT ROLE ANALYST_ROLE  TO ROLE SYSADMIN;

-- ----- Fivetran permissions (write to raw, read nothing else) -----
GRANT USAGE   ON DATABASE ZENDESK_RAW            TO ROLE FIVETRAN_ROLE;
GRANT USAGE   ON SCHEMA   ZENDESK_RAW.ZENDESK    TO ROLE FIVETRAN_ROLE;
GRANT CREATE TABLE ON SCHEMA ZENDESK_RAW.ZENDESK TO ROLE FIVETRAN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA ZENDESK_RAW.ZENDESK  TO ROLE FIVETRAN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON FUTURE TABLES IN SCHEMA ZENDESK_RAW.ZENDESK TO ROLE FIVETRAN_ROLE;

-- ----- dbt permissions (read raw, write analytics) -----
GRANT USAGE   ON DATABASE ZENDESK_RAW            TO ROLE DBT_ROLE;
GRANT USAGE   ON SCHEMA   ZENDESK_RAW.ZENDESK    TO ROLE DBT_ROLE;
GRANT SELECT  ON ALL TABLES IN SCHEMA ZENDESK_RAW.ZENDESK        TO ROLE DBT_ROLE;
GRANT SELECT  ON FUTURE TABLES IN SCHEMA ZENDESK_RAW.ZENDESK     TO ROLE DBT_ROLE;

GRANT USAGE          ON DATABASE ZENDESK_ANALYTICS                TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA   ZENDESK_ANALYTICS.STAGING       TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA   ZENDESK_ANALYTICS.INTERMEDIATE  TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA   ZENDESK_ANALYTICS.MARTS         TO ROLE DBT_ROLE;

-- ----- Analyst permissions (read marts only) -----
GRANT USAGE  ON DATABASE ZENDESK_ANALYTICS                        TO ROLE ANALYST_ROLE;
GRANT USAGE  ON SCHEMA   ZENDESK_ANALYTICS.MARTS                 TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ZENDESK_ANALYTICS.MARTS     TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ZENDESK_ANALYTICS.MARTS  TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ZENDESK_ANALYTICS.MARTS      TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ZENDESK_ANALYTICS.MARTS   TO ROLE ANALYST_ROLE;

-- ----- Service accounts -----
USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS FIVETRAN_USER
    PASSWORD           = 'CHANGE_ME'
    DEFAULT_ROLE       = FIVETRAN_ROLE
    DEFAULT_WAREHOUSE  = ZENDESK_WH
    COMMENT            = 'Fivetran service account';

CREATE USER IF NOT EXISTS DBT_USER
    PASSWORD           = 'CHANGE_ME'
    DEFAULT_ROLE       = DBT_ROLE
    DEFAULT_WAREHOUSE  = ZENDESK_WH
    COMMENT            = 'dbt service account';

USE ROLE SECURITYADMIN;
GRANT ROLE FIVETRAN_ROLE TO USER FIVETRAN_USER;
GRANT ROLE DBT_ROLE      TO USER DBT_USER;
